#############################################################################
# Makefile for building: piuwQt
# Generated by qmake (2.01a) (Qt 4.8.2) on: jeu. mai 1 19:46:51 2014
# Project:  piuwQt.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile piuwQt.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -DEMPL_TARGET_LINUX -DMPU9150 -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Iglue -IMS5803_14BA -IMPU9150 -IAHRS -IeMPL -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/arm-linux-gnueabihf -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = piuwQt.cpp \
		glue/linux_glue.c \
		MS5803_14BA/MS5803_14BA.cpp \
		MPU9150/mpu9150.cpp \
		AHRS/AHRS.cpp \
		eMPL/inv_mpu.c \
		eMPL/inv_mpu_dmp_motion_driver.c 
OBJECTS       = piuwQt.o \
		linux_glue.o \
		MS5803_14BA.o \
		mpu9150.o \
		AHRS.o \
		inv_mpu.o \
		inv_mpu_dmp_motion_driver.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		piuwQt.pro
QMAKE_TARGET  = piuwQt
DESTDIR       = 
TARGET        = piuwQt

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: piuwQt.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/arm-linux-gnueabihf/libQtGui.prl \
		/usr/lib/arm-linux-gnueabihf/libQtCore.prl
	$(QMAKE) -o Makefile piuwQt.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/arm-linux-gnueabihf/libQtGui.prl:
/usr/lib/arm-linux-gnueabihf/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile piuwQt.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/piuwQt1.0.0 || $(MKDIR) .tmp/piuwQt1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/piuwQt1.0.0/ && $(COPY_FILE) --parents glue/linux_glue.h MS5803_14BA/MS5803_14BA.h MPU9150/mpu9150.h AHRS/AHRS.h eMPL/inv_mpu.h eMPL/inv_mpu_dmp_motion_driver.h .tmp/piuwQt1.0.0/ && $(COPY_FILE) --parents piuwQt.cpp glue/linux_glue.c MS5803_14BA/MS5803_14BA.cpp MPU9150/mpu9150.cpp AHRS/AHRS.cpp eMPL/inv_mpu.c eMPL/inv_mpu_dmp_motion_driver.c .tmp/piuwQt1.0.0/ && (cd `dirname .tmp/piuwQt1.0.0` && $(TAR) piuwQt1.0.0.tar piuwQt1.0.0 && $(COMPRESS) piuwQt1.0.0.tar) && $(MOVE) `dirname .tmp/piuwQt1.0.0`/piuwQt1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/piuwQt1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

piuwQt.o: piuwQt.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o piuwQt.o piuwQt.cpp

linux_glue.o: glue/linux_glue.c glue/linux_glue.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o linux_glue.o glue/linux_glue.c

MS5803_14BA.o: MS5803_14BA/MS5803_14BA.cpp MS5803_14BA/MS5803_14BA.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MS5803_14BA.o MS5803_14BA/MS5803_14BA.cpp

mpu9150.o: MPU9150/mpu9150.cpp MPU9150/mpu9150.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpu9150.o MPU9150/mpu9150.cpp

AHRS.o: AHRS/AHRS.cpp AHRS/AHRS.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AHRS.o AHRS/AHRS.cpp

inv_mpu.o: eMPL/inv_mpu.c eMPL/inv_mpu.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o inv_mpu.o eMPL/inv_mpu.c

inv_mpu_dmp_motion_driver.o: eMPL/inv_mpu_dmp_motion_driver.c eMPL/inv_mpu.h \
		eMPL/inv_mpu_dmp_motion_driver.h \
		eMPL/dmpKey.h \
		eMPL/dmpmap.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o inv_mpu_dmp_motion_driver.o eMPL/inv_mpu_dmp_motion_driver.c

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

